# Generated by Django 5.1.2 on 2024-10-25 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("person_name", models.CharField(max_length=100)),
                ("avatar", models.ImageField(upload_to="avatars/")),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("login", models.CharField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("favorite_users", models.ManyToManyField(blank=True, to="api.user")),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pub_date", models.DateField()),
                ("rating", models.IntegerField(default=0)),
                ("commentary", models.TextField()),
                ("is_liked", models.BooleanField(default=False)),
                ("like_count", models.IntegerField(default=0)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.topic"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="api.user",
                    ),
                ),
            ],
        ),
    ]
